name: Second Workflow
on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display some text
              run: echo "Some text"
            - name: Display Node Version on ubuntu
              run: node -v
    run-parallel-command:
        runs-on: windows-latest
        steps:
            - name: Display Node Version on Windsws
              run: node -v
    run-second-command:
        runs-on: macos-latest
        needs: run-first-command
        steps:
            - name: Display Node Version on MacOs
              run: node -v
